Question 1:

Write a program that calculates and prints the value according to the given formula:<br>
Q = Square root of [(2 * C * D)/H]<br>
Following are the fixed values of C and H:<br>
C is 50. H is 30.<br>
D is the variable whose values should be input to your program in a comma-separated
sequence.

Example:<br>
Let us assume the following comma separated input sequence is given to the program:<br>
100,150,180<br>
The output of the program should be:<br>
18,22,24


In [12]:
import re
c=50; h= 30
d= re.split(r'\s*\,\s*', input('Enter values of d: '))

for i in d:
    q= ((2 * c * int(i))/h)**(1/2)
    print(int(round(q, 0)),end=',' if i != d[-1] else '')

Enter values of d:  100, 150, 180


18,22,24

**Question 2:**<br>
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j. Note: i=0,1.., X-1; j=0,1,¡Y-1.

Example<br>
Suppose the following inputs are given to the program:<br>
3,5<br>
Then, the output of the program should be:<br>
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [16]:
import numpy as np
x= int(input('Enter x: '))
y= int(input('Enter y: '))

a = np.zeros((x,y), int)
for i in range (x):
    for j in range (y):
        a[i][j]=i*j
print(a)

Enter x:  3
Enter y:  5


[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


**Question 3:**<br>
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically. Suppose the following input is supplied to the program:<br>
without,hello,bag,world<br>
Then, the output should be:<br>
bag,hello,without,world

In [21]:
print(*sorted(tuple(re.split(r'\s*\,\s*', input('Enter words: ')))))

Enter words:  viresh, raj, sah


raj sah viresh


**Question 4:**<br>
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically. Suppose the following input is supplied to the program:<br>
hello world and practice makes perfect and hello world again<br>
Then, the output should be:<br>
again and hello makes perfect practice world

In [26]:
print(*sorted(set(re.split(r'\s+', input('Enter sentence: ')))))

Enter sentence:  hello world and practice makes perfect and hello world again


again and hello makes perfect practice world


**Question 5:**<br>
Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program:<br>
hello world! 123

Then, the output should be:<br>
LETTERS 10<br>
DIGITS 3

In [29]:
s=input('Enter sentence: ')
print('LETTERS',len([i for i in s if i.isalpha()]))
print('DIGITS',len([i for i in s if i.isnumeric()]))

Enter sentence:  windows 10


LETTERS 7
DIGITS 2


**Question 6:**<br>
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.<br>
Following are the criteria for checking the password:<br>
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example:<br>
If the following passwords are given as input to the program:<br>
ABd1234@1,a F1#,2w3E*,2We3345<br>
Then, the output of the program should be:<br>
ABd1234@1

In [31]:
def is_correct_password(s):
    minlen=len(s)>=6
    maxlen=len(s)<=12
    hassmall=len(re.findall(r'([a-z])',s))>=1
    hascaps=len(re.findall(r'([A-Z])',s))>=1
    hassplchar=len(re.findall(r'([$#@])',s))>=1
    if minlen and maxlen and hassmall and hascaps and hassplchar:
        return s

d= re.split(r'\s*\,\s*', input('Enter passwords: '))
print (*[i for i in d if is_correct_password(i)])

Enter passwords:  ABd1234@1,a F1#,2w3E*,2We3345


ABd1234@1
