1. Write a Python Program to find sum of array?
2. Write a Python Program to find largest element in an array?
3. Write a Python Program for array rotation?
4. Write a Python Program to Split the array and add the first part to the end?
5. Write a Python Program to check if given array is Monotonic?

In [2]:
# 1
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
a.sum()

45

In [3]:
# 2
a.max()

9

In [48]:
# 3
def rotatearray(a, k):
    tail=list(a[-k:])
    head=list(a[:-k])
    
    tail.extend(head)
    return np.array(tail)

rotatearray(a, -5)

array([6, 7, 8, 9, 1, 2, 3, 4, 5])

In [50]:
# 4
def split_concat(a, k):
    head= list(a[:k])
    tail= list(a[k:])
    tail.extend(head)
    return np.array(tail)

split_concat(a, 2)

array([3, 4, 5, 6, 7, 8, 9, 1, 2])

In [56]:
# 5
def checkmono(a):
    if list(a)==list(sorted(a, reverse=False)) or list(a)==list(sorted(a, reverse=False)):
        return True
    else:
        return False

arr1= np.array([1,2,3,4,5,6,7])
arr2= np.array([1,3,6,8,2])
arr3= np.array([8,6,5,3,2,1])

print(arr1, 'is monotonic' if checkmono(arr1) else 'is not momotonic')
print(arr2, 'is monotonic' if checkmono(arr2) else 'is not momotonic')
print(arr3, 'is monotonic' if checkmono(arr3) else 'is not momotonic')

[1 2 3 4 5 6 7] Is monotonic
[1 3 6 8 2] is not momotonic
[8 6 5 3 2 1] is not momotonic


In [59]:
list(arr3)==list(sorted(arr3, reverse=True))

True

In [60]:
list(arr3), list(sorted(arr3, reverse=True))

([8, 6, 5, 3, 2, 1], [8, 6, 5, 3, 2, 1])