1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [10]:
# 1
import numpy as np

def matsum(m1,m2):
    l=len(m1)
    b=len(m1[0])
    sum=np.zeros((l,b))
    for i in range(l):
        for j in range(b):
            sum[i][j]=m1[i][j]+m2[i][j]
    return sum
    
m1=np.arange(1,10).reshape(3,3)
m2=np.arange(20,29).reshape(3,3)
    
print(matsum(m1,m2))

[[21. 23. 25.]
 [27. 29. 31.]
 [33. 35. 37.]]


In [26]:
#2
def matmul(m1,m2):
    l1=len(m1)
    b1=len(m1[0])
    l2=len(m2)
    b2=len(m2[0])
    
    prod=np.zeros((l1,b2))
    if b1==l2:
        for i in range(l1):
            for j in range(b2):
                for k in range(b1):
                    prod[i][j] = m1[i][k] * m2[k][j]
    return prod
matmul(m1,m2)     

array([[ 78.,  81.,  84.],
       [156., 162., 168.],
       [234., 243., 252.]])

In [27]:
# 3
def tr(m):
    l,b = m.shape
    n=np.zeros((b,l))
    for i in range(l):
        for j in range(b):
            n[j][i]=m[i][j]
    return n
tr(m1)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [31]:
# 4
def alphaorder(s):
    return sorted(s.split(' '))
s = input('Enter a string: ')
alphaorder(s)

Enter a string:  my name is Viresh


['Viresh', 'is', 'my', 'name']

In [34]:
# 5
import re
def scremove(s):
    return re.sub(r'\W', '', s, flags=re.X)
    
s = input('Enter a string: ')
scremove(s)

Enter a string:  emo'.vs\]:sno


'emovssno'